### ISSUE TITLE
Library to format and paginate tabular CLI output

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/request-for-implementation#15]
In [`cargo llvm-lines`](https://github.com/dtolnay/cargo-llvm-lines) the program output is a table with two columns of numbers and one column of strings. I would like a super easy way to make such output look good with the minimal amount of work in my crate. Something like:

```rust
pub fn cli_table(data: Vec<Vec<String>>) -> !;
```

which takes care of aligning the data (right aligned for columns of numbers, left aligned for text), drawing ASCII art to make it pretty (like what [`bat`](https://github.com/sharkdp/bat) does), and invoking the default system pager to support paging the output up and down (again similar to `bat`).

If the output is not [a tty](https://github.com/softprops/atty), the paging and ASCII art should be disabled automatically.

**Comment by RazrFalcon** [comment]
There is [prettytable-rs](https://crates.io/crates/prettytable-rs). But it's pretty simple.

**Comment by dtolnay** [comment]
Thanks, prettytable-rs looks pretty close to what I want. I like the subtle unicode line art that `bat` uses. Is that doable as a prettytable format?

<br>

<p align="center">
<img alt="bat screenshot" src="https://camo.githubusercontent.com/9d3d89364f2cc83ace8f29646a6236bc15ea1da0/68747470733a2f2f696d6775722e636f6d2f724773646e44652e706e67" width="75%">
</p>

**Comment by RazrFalcon** [comment]
I newer used it. I wanted to use it in `cargo-bloat`, but it doesn't support column width, which I need.

**Comment by gfreezy** [comment]
https://github.com/phsym/prettytable-rs/blob/fa70ca6fdb7d0d98a04961c1a74105e4f797661d/examples/formatting.rs#L64

`prettytable-rs` can print `bat` like lines.

**Comment by dtolnay** [comment]
Thanks all! I have removed this idea from my list since it is easily solved by using the `prettytable-rs` crate + `pager` crate which already existed when I opened this issue.
