### ISSUE TITLE
Testing tool for comparing output of macro against expected source code

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/request-for-implementation#28]
Similar to what https://github.com/dtolnay/trybuild does for testing compilation failures. 

See [here](https://github.com/dtolnay/serde-repr/blob/c0bdb4bc6290c678ae74125434af1b4deeb3871c/tests/compiletest.rs) and [here](https://github.com/dtolnay/serde-repr/tree/c0bdb4bc6290c678ae74125434af1b4deeb3871c/tests/ui) for a basic test setup leveraging trybuild.

I would expect a very similar setup for testing macro expansion -- with a suite of test cases as \*.rs files in some directory, adjacent to expected expanded output in \*.expanded.rs files with corresponding names. For each test case the library would set up dependencies and stuff correctly then invoke [cargo expand](https://github.com/dtolnay/cargo-expand) to expand macros and format the expanded code with rustfmt. Then the test case would fail if the expanded and formatted code differs from the expected output in the corresponding \*.expanded.rs file.

**Comment by dtolnay** [comment]
This is better than invoking proc macros directly as `fn(TokenStream) -> TokenStream` from tests for a few reasons:

- It supports testing macro_rules macros as well.
- It does not require factoring testable code out of your `proc-macro = true` entry point crate solely for testing purposes. We can test the proc macro crate directly.
- The tool can provide a simple command which automatically updates all the \*.expanded.rs files to account for changes in the macro's implementation.

**Comment by eupn** [comment]
@dtolnay I want to give it a try. It's ok?

**Comment by dtolnay** [comment]
Sounds good! Thanks for taking a look.

**Comment by eupn** [comment]
@dtolnay `macrotest` repository is here: https://github.com/eupn/macrotest. I have quick-and-dirty version done and simple `macro_rules!` macro expansion test project here: https://github.com/eupn/macrotest/tree/master/test-project/tests, check it out.

**Comment by eupn** [comment]
Oh, I see that you've updated the issue's description. I will update the `macrotest`'s API to resemble the `trybuild` closely.

**Comment by eupn** [comment]
Updated the API to be similar to `trybuild`. https://github.com/eupn/macrotest/blob/master/test-project/tests/tests.rs

@dtolnay what should be considered as "expected failure" case of `cargo expand` invocation? Any non-success return code? Or should we add a comparison with `.stderr` file?

**Comment by dtolnay** [comment]
There are no expected failures. If any cargo expand exits unsuccessful then it should fail the test.

**Comment by eupn** [comment]
Published to crates.io: [macrotest](https://crates.io/crates/macrotest)

**Comment by eupn** [comment]
Added [procedural macro example](https://github.com/eupn/macrotest/tree/master/test-procmacro-project). Though it has some issues ([#6](https://github.com/eupn/macrotest/issues/6), [#7](https://github.com/eupn/macrotest/issues/7)), it works.

**Comment by dtolnay** [comment]
Nice, looks like a great start. I filed some issues based on trying out the crate. I think we can close out this issue once those are fixed. Thanks!

**Comment by eupn** [comment]
Thanks for the thorough review! Will fix as many as possible.

**Comment by eupn** [comment]
@dtolnay issues are fixed

**Comment by dtolnay** [comment]
Awesome!

**Comment by eupn** [comment]
@dtolnay btw, which of your crates with macros/proc-macros (or crates that you know) would make use of this tool? I'd be happy to file a PR to some of those crates to employ `macrotest` in them.

**Comment by dtolnay** [comment]
I would like to try it in Serde because the logic inside Deserialize derives can be pretty complicated to reason about. https://github.com/serde-rs/serde/issues/1117
