### ISSUE TITLE
Tool to enforce that Cargo.toml dependencies are written in sorted order

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/request-for-implementation#29]
```console
$ cargo dependencies-sorted? path/to/Cargo.toml; echo $?
0
```

Large projects tend to like for things to stay sorted to cut down the occurrence of merge conflicts between two developers appending to the end of the same unsorted list in parallel changes. Similar idea behind the [remain](https://github.com/dtolnay/remain) crate.

The command should parse a Cargo.toml and validate that particular pieces are sorted, exiting 0 if all sorted and nonzero otherwise.

We would at least want to check:

- `[dependencies]`
- `[dev-dependencies]`
- `[build-dependencies]`
- `[workspace.members]`
- `[workspace.exclude]`

Take a look at the documentation for Cargo.toml to see whether any other parts make sense to enforce as sorted.

**Comment by jpoles1** [comment]
I'm somewhat new to Rust, but I'd like to try to take a stab at this one as a way to learn some more!

**Comment by dtolnay** [comment]
Yay! Let me know how it goes or if you get stuck on any part.

**Comment by jpoles1** [comment]
Thanks @dtolnay! Will keep you updated as the project progresses.

**Comment by jpoles1** [comment]
Still working on some of the basic functionality, and I've gotta write tests for everything, but I've got a prototype up and running at this repo: https://github.com/jpoles1/cargo-dep-sort

As a note, I had originally wanted to use the [TOML crate](https://crates.io/crates/toml), but as far as I can tell, parsing with this library does not respect the order of the TOML tables, and as such is not suitable for this application. It looks like it's [possible to enable preservation of ordering](https://docs.rs/toml/0.5.0/toml/value/type.Table.html), but this is an experimental feature, and thus requires nightly rustc builds to work, which I wanted to avoid for the time being.

**Comment by dtolnay** [comment]
You will need to use the toml crate. Regex are not a reliable way to interpret a TOML file. The preserve_order feature is neither experimental nor requires nightly. You can turn it on as:

```toml
[dependencies]
toml = { version = "0.5", features = ["preserve_order"] }
```

**Comment by jpoles1** [comment]
Ok, will give that try, thanks for the guidance!

**Comment by jpoles1** [comment]
Nothing perfect, but I've got the basic functionality up and running using the toml crate. My big concern right now is writing tests.

One other thing I'm having some trouble with is a feature to write sorted Cargo.toml files out of the software. The big issue is that the serialization features of the toml crate are limited, such that you can't use inline tables (like the toml dep line you suggested to me above). Still trying to work out a way around that.

**Comment by pickfire** [comment]
Should this be in clippy instead?

**Comment by polybuildr** [comment]
In case it helps, in https://github.com/rust-lang/rust/issues/57443#issuecomment-476892723 I came across the [toml_edit crate](https://crates.io/crates/toml_edit/) (a format preserving TOML parser that [cargo-edit](https://crates.io/crates/cargo-edit) uses). It has some issues but works well overall.

**Comment by gsquire** [comment]
I decided to give this a go and published an initial version [here](https://github.com/gsquire/toml-sorted). I will add some unit tests soon and ensure that it works as expected. Please file issues if you find any!

**Comment by dtolnay** [comment]
Thanks @gsquire! I wasn't able to get it working (https://github.com/gsquire/toml-sorted/issues/2) but once that works I'll close out this issue.

**Comment by DevinR528** [comment]
I added some to @jpoles1, implementation wondering if I'm moving in the right direction https://github.com/DevinR528/cargo-dep-sort. Rewriting the file is the idea correct? Having it work like cargo itself, by assuming everything from cwd, is probably the most erganomic?

**Comment by dtolnay** [comment]
In my case I wouldn't want it rewriting the file, just a reliable 0 or 1 exit code and consideration for common patterns like out-of-line dependency sections (syn in [cargo-expand/Cargo.toml](https://github.com/dtolnay/cargo-expand/blob/0.4.12/Cargo.toml)).

**Comment by DevinR528** [comment]
So fail if:
```toml
[dependencies.b]
version = "0.15"

[dependencies.a]
version = "0.15"
```

**Comment by dtolnay** [comment]
Yes I would want that to exit nonzero. The out-of-line dependencies should need to be sorted among themselves.

**Comment by Zykino** [comment]
Maybe it is not your use case but having an option to override the file could be nice. Or at least write the correct order somewhere: console/file.

**Comment by DevinR528** [comment]
Here's my crack at sort checking cargo.toml you can install it ```bash cargo install cargo-sort-ck```. I'm glad I found this repo any excuse to write some rust is a good one thanks @dtolnay.  @Zykino I also started adding that feature to https://github.com/DevinR528/cargo-dep-sort cloned from @jpoles1.

**Comment by DevinR528** [comment]
[cargo-sort-ck](https://github.com/DevinR528/cargo-sort-ck) now has a toml tokenizer, as such can handle comments, nested headers, out of group nested headers and each "token" impls display so printing to a file would be as easy as .to_string().

**Comment by DevinR528** [comment]
[cargo-sort-ck](https://github.com/DevinR528/cargo-sort-ck) is finished, other than bug fixes.  Any feed back would be much appreciated, working alone can create a real echo chamber.

Thanks

**Comment by dtolnay** [comment]
Thanks @DevinR528! This is terrific. I filed some issues for you but I am really impressed by your crate.
