### ISSUE TITLE
A crate to inline all modules into a single file.

### ISSUE THREAD

**Issue by crlf0710** [dtolnay/request-for-implementation#39]
A crate maybe called cargo-fuse, that can read all modules within a crate, and "fuse" them into a single `.rs` file. It'll be great if it can also generate the header describing the dependencies, something existing tools like `cargo-script` needs.

**Comment by frol** [comment]
There are already at least three such projects:

* https://github.com/slava-sh/rust-bundler
* https://github.com/lpenz/rust-sourcebundler
* https://github.com/MarcosCosmos/cg-rust-bundler

Though, none of them are maintained anymore as far as I see.

**Comment by dtolnay** [comment]
I'll give this a close as it seems this already exists. I would recommend filing feature requests on one of those existing projects as needed. Thanks!
