### ISSUE TITLE
A proc macro that automatically generates a sync version for an async function.

### ISSUE THREAD

**Issue by crlf0710** [dtolnay/request-for-implementation#41]
Thus workaround the "what color is your function" problem.

**Comment by dtolnay** [comment]
Could you write up a brief example of what you would like for the caller to write and exactly what it should expand to?

**Comment by crlf0710** [comment]
Admittedly i've not got enough knowledge to come up with a design on this... I hope others can come up with a detailed design.

**Comment by dtolnay** [comment]
I'd like to keep this repo focused just on ideas that are blocked on implementation work and not design work, so I will go ahead and close this for now. Let's follow up once there is a more fleshed out design for what you want.
