### ISSUE TITLE
A proc macro that mirrors the functionality of the unstable `trace_macros` macro.

### ISSUE THREAD

**Issue by crlf0710** [dtolnay/request-for-implementation#42]
It may help a lot of people by moving these complexity out of the compiler, and improve it.
https://github.com/rust-lang/rust/issues/29598

**Comment by dtolnay** [comment]
:( I don't know a good way that this would be implemented. This would be amazing to have, but I think this idea is more researchy/underspecified than I would prefer for tracking in this repo. Thanks anyway!
