### ISSUE TITLE
a procedural macro for creating extension traits

### ISSUE THREAD

**Issue by nikomatsakis** [dtolnay/request-for-implementation#43]
I would like a macro where

```rust
#[private_extension(Foo)]
impl SomeExternalType {
    fn method(&self) { ... }
}
```

would expand to 

```rust
trait Foo {
    fn method(&self);
}

impl Foo for SomeExternalType { ..  }
```

**Comment by taiki-e** [comment]
I think [easy-ext](https://crates.io/crates/easy-ext/) is exactly the crate for this.

**Comment by dtolnay** [comment]
Yep, that looks like it. Thanks! https://crates.io/crates/extend is another implementation.
