### ISSUE TITLE
A golang-style iota macro.

### ISSUE THREAD

**Issue by crlf0710** [dtolnay/request-for-implementation#45]
Not really sure how useful is this. Just an idea at the moment.
There's an outdated nightly crate with similar functionality at https://github.com/Popog/iota-rs .
Example:
```
fn foo() -> usize {
    #![iota_scope(name = "iota", initial_value = "3")]
    let a = iota!();  // expands to literal 3
    let b = iota!();  // expands to literal 4
    a + b + iota!()    // expands to literal 5
}
```

**Comment by dtolnay** [comment]
I am going to close this because I would like to keep this repository focused on worthwhile ideas that someone is looking forward to using as soon as an implementation exists, and as you said it's unclear that an iota macro would be useful in Rust.

**Comment by dtolnay** [comment]
FWIW https://github.com/dtolnay/iota has my old implementation of iota that does not rely on plugins.
