### ISSUE TITLE
Modules defined by combining multiple files.

### ISSUE THREAD

**Issue by crlf0710** [dtolnay/request-for-implementation#47]
Define a proc macro that collects and combines multiple sources into a single module.
```rust
// lib.rs

#[paths("a.rs", "b.rs")]
mod foo;

// a.rs
//! inner docstring comment 1
struct Part1;

// b.rs
//! inner docstring comment 2

struct Part2;
```

got expanded into (with proper `Span`s if possible):

```rust
// lib.rs
mod foo {
    //! inner docstring comment 1
    //! inner docstring comment 2

    struct Part1;
    struct Part2;
}

**Comment by CreepySkeleton** [comment]
What it would be useful for?

**Comment by dtolnay** [comment]
I think any implementation of this would destroy all the spans, so I am skeptical that a macro would be worthwhile.

**Comment by dtolnay** [comment]
A workaround would be to write:

```rust
mod foo {
    //! inner docstring comment 1
    //! inner docstring comment 2

    mod a;
    mod b;

    pub use a::*;
    pub use b::*;
}
```

**Comment by crlf0710** [comment]
that's a little different, with the current visibility rules, some arrangement needs to be done in a.rs and b.rs to make them work together. (Additional `use`s, for example.) But it will mostly work.

Too bad `Span` referring to external files cannot be created. I left a ticket in https://github.com/rust-lang/rfcs/issues/2869 .
