### ISSUE TITLE
A new linker in Rust

### ISSUE THREAD

**Issue by lzutao** [dtolnay/request-for-implementation#49]
A faster linker may improve compile time of Rust. 
There are experimental on integrate lld as default default linker for Rust, which is tracked at https://github.com/rust-lang/rust/issues/39915.
But `lld` has it own problems: https://github.com/rust-lang/rust/issues?page=2&q=is%3Aissue+is%3Aopen+lld+label%3AA-linkage

I don't know how hard it be to implement a cross-platform linker. But this may be a fun project to try.

**Comment by dtolnay** [comment]
A brand new cross-platform linker is a bigger project than I would prefer to track in this repo. Thanks anyway!
