### ISSUE TITLE
Find rustup components installed under a different toolchain

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/request-for-implementation#5]
In https://github.com/dtolnay/cargo-expand/issues/39 I need to look for any `rustfmt` that may be installed on the system.

Currently what happens is that if the user has `rustup component add rustfmt --toolchain stable` but is running `cargo +nightly expand`, then somehow Cargo sets up the subcommand environment such that simply running `Command::new("rustfmt")` will end up running a shim that only tells you there is no rustfmt installed for the nightly toolchain. The thing is, I don't care whether the rustfmt I run is from the same toolchain as the cargo-expand binary. I would happily run the stable toolchain's rustfmt from the nightly toolchain's cargo-expand if I knew the path to the right binary.

```rust
pub fn find_installed_component(name: &str) -> Option<PathBuf>;
```

Intended usage:

```rust
use std::process::Command;

let which_rustfmt = find_installed_component("rustfmt");
match which_rustfmt {
    None => {
        /* there is no rustfmt on any toolchain */
    }
    Some(rustfmt) => {
        Command::new(rustfmt).args(...).spawn();
    }
}
```

This will be relevant to other Cargo subcommands too, so the implementation should go in a crate rather than directly in cargo-expand.

**Comment by gsquire** [comment]
I think I can give this a spin but I wanted to ask a question. If the user has more than two toolchains installed and runs expand under nightly which does not have `rustfmt` but the other two toolchains do, does it matter which toolchain gets picked?

**Comment by dtolnay** [comment]
I would go for whichever toolchain reports the highest rustc version number. For example the rustc versions might be:

- rustc 1.33.0-beta.3 (4df66ba86 2019-01-21)
- rustc 1.32.0 (9fda7c223 2019-01-16)

in which case (for my use case) I would prefer to use rustfmt from 1.33.0-beta.3.

**Comment by gsquire** [comment]
I worked on a prototype for a little bit. I know it's rough around the edges but I think it does what you have outlined in this issue. The example runs and prints out some components that I had on my system.

Here is the repository: https://github.com/gsquire/toolchain_find

**Comment by gsquire** [comment]
Sure, I'll see how that all goes and share the PR here when I think it's complete.

**Comment by gsquire** [comment]
I was able to successfully go through that test case and it worked as intended. Hopefully you can reproduce it as well. The PR is: https://github.com/dtolnay/cargo-expand/pull/45

**Comment by dtolnay** [comment]
Nicely done. I will close out this issue and mark it off the list.

I filed https://github.com/gsquire/toolchain_find/issues/1 for one small follow up.
