### ISSUE TITLE
Library to inline out-of-line mod items and resolve #[path = "..."]

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/request-for-implementation#6]
In https://github.com/dtolnay/cargo-expand/issues/11 I need to be able to take a source file as a [`syn::File`](https://docs.rs/syn/0.15/syn/struct.File.html) and transitively expand every `mod m;` into `mod m { ... }` with its contents drawn from the right file.

Concretely we'll be replacing the [`content` field of every `ItemMod`](https://docs.rs/syn/0.15/syn/struct.ItemMod.html) with Some if it is None.

Example input:

#### src/lib.rs

```rust
#[cfg(feature = "m1")]
mod m1;

#[cfg_attr(feature = "m2", path = "m2.rs")]
#[cfg_attr(not(feature = "m2"), path = "empty.rs")]
mod placeholder;
```

#### src/m1.rs

```rust
struct M1;
```

#### src/m2.rs

```rust
//! module level doc comment

struct M2;
```

#### src/empty.rs

```rust
// empty file
```

The result will look like:

```rust
#[cfg(feature = "m1")]
mod m1 {
    struct M1;
}

#[cfg(feature = "m2")]
mod placeholder {
    //! module level doc comment

    struct M2;
}

#[cfg(not(feature = "m2"))]
mod placeholder {
}
```

Possible API:

```rust
pub fn parse_and_inline_modules(root: &std::path::Path) -> syn::File;
```

**Comment by TedDriggs** [comment]
I'll take a look at this one.

**Comment by TedDriggs** [comment]
Should this be done recursively?

How should not-found files be handled? They could be made into empty modules, or the top-line API could be changed to return a `Result`.

**Comment by dtolnay** [comment]
Yes I would like it to be recursive.

For my use case I would want not-found modules to simply stay as `mod m;` and for the top-level API to be infallible. Performing this transformation 100% correctly requires more parts of a compiler (including name resolution and macro expansion), so since only an approximation is being implemented, there is no meaningful way that a caller could handle failures.

**Comment by TedDriggs** [comment]
https://github.com/TedDriggs/syn-inline-mod

**Comment by TedDriggs** [comment]
Making it explicit: `syn-inline-mod` hits all the requirements from this one, so I think it's ready to close.

**Comment by TedDriggs** [comment]
Found a couple bugs; filing them over in the crate repo.

**Comment by dtolnay** [comment]
@dpc is https://docs.rs/syn-inline-mod sufficient for your use case or do you need it to be integrated into a cli?

**Comment by dpc** [comment]
@dtolnay After I'll figure out how to convert it to string, and how to find entry points to a given crate, I'll be all set. :)

**Comment by TedDriggs** [comment]
@dpc I've been calling `into_token_stream().to_string()` on the `syn::File` instance to get the results into a string.

**Comment by dtolnay** [comment]
I don't know what is the best way to find out the crate entry point. This may be a Cargo feature request. The following might work for now:

```rust
cargo +nightly build -Z unstable-options --build-plan \
    | jq -r '.invocations[-1].args[2]'
```

**Comment by dpc** [comment]
Thanks!

**Comment by dtolnay** [comment]
Added link in the readme. Nicely done!
